### ISSUE TITLE
Issue with Evaluation Code for 16-bit PNG Images

### ISSUE THREAD

**Issue by y-kage** [SoccerNet/sn-depth#1]
Hi, thanks for holding such an interesting challenge! I’ve been excited to participate, but I've encountered two issues while evaluating the predictions using the provided evaluation code:

1. In the code section below, it seems like the code is intended to accept only 16-bit PNG images, but it doesn't currently handle the "I;16" mode correctly. When I changed "I" to "I;16", the code accepted the 16-bit PNG images. Shouldn't it be checking for "I;16" instead of just "I"?
# https://github.com/SoccerNet/sn-depth/blob/4cab8582f27e1015af2cbfe71ac72ae47ebc44aa/evaluation/utils.py#L19-L20

2. In the final stage, the code is returning tensors with values in the range of [-32768, 32767], whereas  the downstream code expects the tensor to be in the range of [0, 65535] (16-bit unsigned integer). This causes the evaluation metrics to return nan. I've modified the code to return the tensor in the correct range. Is this a valid solution, and is this adjustment appropriate for the intended behavior?
# https://github.com/SoccerNet/sn-depth/blob/4cab8582f27e1015af2cbfe71ac72ae47ebc44aa/evaluation/utils.py#L21

Here’s the change I made to fix these issues:

```bash
class ImageDataset(Dataset):
    def __init__(self, image_files):
        self.image_files = image_files
        self.transform = transforms.ToTensor()

    def __len__(self):
        return len(self.image_files)

    def __getitem__(self, idx):
        img = Image.open(self.image_files[idx])
        img_mode = img.mode
        # print(f"Mode: {img.mode}")
        if img_mode != "I;16":
            raise ValueError(f"Image {self.image_files[idx]} is not a 16-bit PNG image")
        img_data = np.array(img)
        tensor = torch.from_numpy(img_data).float()
        return tensor
```

I made this modification, and the results I’m getting are no longer nan. The orders of magnitude seem correct when compared to the results in the paper, but I'm not sure if the results are accurate. Could you please verify if this modification is correct, or suggest an alternative approach to handle this?

Thanks!

**Comment by SilvioGiancola** [comment]
Hi @y-kage, thank you for reaching out and give the depth challenge a try! I would leave @Arnaudldc to answer your questions. Cheers!

**Comment by y-kage** [comment]
I also changed test_score.txt and evaluation.py because the path is not reusable in different environments. Could you also check this?

https://github.com/SoccerNet/sn-depth/blob/4cab8582f27e1015af2cbfe71ac72ae47ebc44aa/evaluation/test_score.txt#L1-L5
to
```bash
foot_game_17_video_1_depth_r_1.png
foot_game_17_video_1_depth_r_2.png
foot_game_17_video_1_depth_r_3.png
foot_game_17_video_1_depth_r_4.png
foot_game_17_video_1_depth_r_5.png
```

and
https://github.com/SoccerNet/sn-depth/blob/4cab8582f27e1015af2cbfe71ac72ae47ebc44aa/evaluation/evaluation.py#L62
to
```bash
gt_file = gt_files[i]
gt_file = gt_file.split("/")[-1]
```

Thanks!

**Comment by Arnaudldc** [comment]
Hi @y-kage, 

Thank you very much for your interest in our project and the insights provided !

"_In the code section below, it seems like the code is intended to accept only 16-bit PNG images, but it doesn't currently handle the "I;16" mode correctly. When I changed "I" to "I;16", the code accepted the 16-bit PNG images. Shouldn't it be checking for "I;16" instead of just "I"?_"

Indeed, that was an issue that we are going to change in the evaluation code for the competition. The fix should be enough to make it work.

"_In the final stage, the code is returning tensors with values in the range of [-32768, 32767], whereas the downstream code expects the tensor to be in the range of [0, 65535] (16-bit unsigned integer). This causes the evaluation metrics to return nan. I've modified the code to return the tensor in the correct range. Is this a valid solution, and is this adjustment appropriate for the intended behavior?_"

I am sorry for the inconvenience, I tried it with your solution and mine, and I got the same solution. We will adapt the code to make it more generic. Thank you for your input. Your results should however be correct, now!


Looking at the test_score.txt, it is indeed meant to be an example that need to be adapted to your environment. Your transformation looks good.

Thank you again for the remark that will enable to enhance the code, and hope you will enjoy our challenge!
